vich_uploader:
    db_driver: orm

    mappings:
       quizz_image:
           uri_prefix: '%app.path.quizz_images%'
           upload_destination: '%kernel.project_dir%/public%app.path.quizz_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
